AllCops:
  CacheRootDirectory: tmp
  DisplayCopNames: true
  Exclude:
    - .git/**/*
    - gemfiles/vendor/**/*
    - vendor/**/*
  TargetRubyVersion: 2.3

# Configured cops

Layout/IndentHash:
  EnforcedStyle: consistent

Lint/EndAlignment:
  Enabled: variable

Naming/FileName:
  Exclude:
    - 'lib/active_record_shards/patches-4-2.rb'
    - 'lib/active_record_shards/connection_switcher-4-2.rb'
    - 'lib/active_record_shards/connection_switcher-5-0.rb'
    - 'lib/active_record_shards/connection_switcher-5-1.rb'

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: percent

# Disabled cops

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
