require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  CacheRootDirectory: tmp
  Exclude:
    - .git/**/*
    - gemfiles/vendor/**/*
    - vendor/**/*
  TargetRubyVersion: 2.5

# Configured cops

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - table

Naming/FileName:
  Exclude:
    - 'lib/active_record_shards/connection_switcher-5-0.rb'
    - 'lib/active_record_shards/connection_switcher-5-1.rb'
    - 'lib/active_record_shards/connection_switcher-6-0.rb'

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: percent

# Disabled cops

Lint/AssignmentInCondition:
  Enabled: false

Metrics:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
