require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  CacheRootDirectory: tmp
  Exclude:
    - .git/**/*
    - gemfiles/vendor/**/*
    - vendor/**/*
  NewCops: disable
  TargetRubyVersion: 2.6

Layout: {Enabled: false}
Metrics: {Enabled: false}
Style: {Enabled: false}

Lint/AssignmentInCondition: {Enabled: false}

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/**/*'

Naming/FileName:
  Exclude:
    - 'lib/active_record_shards/connection_switcher-5-1.rb'
    - 'lib/active_record_shards/connection_switcher-6-0.rb'
    - 'lib/active_record_shards/connection_switcher-6-1.rb'
    - 'lib/active_record_shards/connection_switcher-7-0.rb'
