name: Publish Gem

on:
  push:
    tags: v*

jobs:
  call-workflow:
    uses: zendesk/gw/.github/workflows/ruby-gem-publication.yml@main
    secrets:
      RUBY_GEMS_API_KEY: ${{ secrets.RUBY_GEMS_API_KEY }}
      RUBY_GEMS_TOTP_DEVICE: ${{ secrets.RUBY_GEMS_TOTP_DEVICE }}
